### ISSUE TITLE
Uncaught RangeError: invalid date

### ISSUE THREAD

**Issue by izaktan** [react-auth-kit/react-auth-kit#873] opened 2022-03-19 09:24 UTC
When the auth kit is dealing with the response, I got "Uncaught RangeError: invalid date". Does it require server to specifically return the expires attributes? Is there a way to use the Set-Cookies attribute in the response directly?

**Expected behavior**
No error

**Additional context**
In the console:
```
Uncaught RangeError: invalid date
setCookieToken_ TokenObject.ts:321
setToken TokenObject.ts:275
syncTokens TokenObject.ts:243
AuthProvider AuthProvider.tsx:69
```

In the response: 
`Set-Cookie: xxx_session=xxxx;  expires=Sun, 20-Mar-2022 09:03:48 GMT; Max-Age=86400; path=/; httponly;  samesite=lax`

**Comment by darkmatter18** [comment] 2022-03-22 12:36
Can you please send your login code snippet? It'll be helpful

**Comment by izaktan** [comment] 2022-04-03 06:37
I think this is where my problem is. I don't know how to get token and expiresIn since access to set-cookie header is blocked by browsers. So my question is is it expected for the server to return token and expireIn as data of the response even though these information already in header

``` 
axios.post('login', formData, {withCredentials: true})
      .then((res) => {
        if (res.status === 200) {
          console.log(res.headers['set-cookie'])
          if (signIn({
            token: res.data.token,
            expiresIn: res.data.expiresIn,
            tokenType: "Bearer",
            authState: res.data.authUserState,
            // refreshToken: res.data.refreshToken,                    // Only if you are using refreshToken feature
            // refreshTokenExpireIn: res.data.refreshTokenExpireIn     // Only if you are using refreshToken feature
          })) { 
            // Redirect or do-something
          } else {
            console.log("error")
            // Throw error
          }
        } else {
          console.log(res.data)
        }
      })
```

**Comment by izaktan** [comment] 2022-04-03 09:55
To be more clear, I am currently using Laravel as my backend. However the document says that "You should not use API tokens to authenticate your own first-party SPA. Instead, use Sanctum's built-in [SPA authentication features](https://laravel.com/docs/9.x/sanctum#spa-authentication)." So I am a bit confused about what the **token** in the signIn component is supposed to be in my case now.

**Comment by essalah** [comment] 2022-04-22 22:22
same thing, any solution please

**Comment by essalah** [comment] 2022-04-23 09:16
Hi, in my case the problem is about the expiresIn field of the token, the backend server present it as milliseconds "timestamp",
for this reason we got this error with "invalid date" by React auth kit,
My solution here is convert the token expires date to minutes before assign it , see my example below:
`...
const getExpiresDateByMinutes = (timestampDate: number) => {
    const diff = timestampDate - (new Date().getTime());
    const expiresOnMinutes = diff / (1000 * 60 * 60);
    return expiresOnMinutes;
}
..
const Login = () => {
...
signIn({
                        token: response.data.token,
                        expiresIn: **getExpiresDateByMinutes**(response.data.expiresIn),
                        tokenType: "Bearer"
                    })
...

}
..

`

**Comment by darkmatter18** [comment] 2022-04-26 15:50
Great Answer by @essalah . `UseSignIn` `expiresIn` parameter expects a time in minutes.

**Closed** 2022-05-12 17:07 UTC
